package com.future.link.convenience.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePublish<M extends BasePublish<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setCategoryId(java.lang.Long categoryId) {
		set("categoryId", categoryId);
	}

	public java.lang.Long getCategoryId() {
		return get("categoryId");
	}

	public void setImageUrl(java.lang.String imageUrl) {
		set("imageUrl", imageUrl);
	}

	public java.lang.String getImageUrl() {
		return get("imageUrl");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setTopStatus(java.lang.Integer topStatus) {
		set("topStatus", topStatus);
	}

	public java.lang.Integer getTopStatus() {
		return get("topStatus");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setHeadUrl(java.lang.String headUrl) {
		set("headUrl", headUrl);
	}

	public java.lang.String getHeadUrl() {
		return get("headUrl");
	}

	public void setBrowseNum(java.lang.Integer browseNum) {
		set("browseNum", browseNum);
	}

	public java.lang.Integer getBrowseNum() {
		return get("browseNum");
	}

	public void setPraiseNum(java.lang.Integer praiseNum) {
		set("praiseNum", praiseNum);
	}

	public java.lang.Integer getPraiseNum() {
		return get("praiseNum");
	}

	public void setNoPraiseNum(java.lang.Integer noPraiseNum) {
		set("noPraiseNum", noPraiseNum);
	}

	public java.lang.Integer getNoPraiseNum() {
		return get("noPraiseNum");
	}

}
