package com.future.link.carousel.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdvertising<M extends BaseAdvertising<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setLinkedUrl(java.lang.String linkedUrl) {
		set("linkedUrl", linkedUrl);
	}

	public java.lang.String getLinkedUrl() {
		return get("linkedUrl");
	}

	public void setShowPosition(java.lang.Integer showPosition) {
		set("showPosition", showPosition);
	}

	public java.lang.Integer getShowPosition() {
		return get("showPosition");
	}

	public void setSortNum(java.lang.Integer sortNum) {
		set("sortNum", sortNum);
	}

	public java.lang.Integer getSortNum() {
		return get("sortNum");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setImageUrl(java.lang.String imageUrl) {
		set("imageUrl", imageUrl);
	}

	public java.lang.String getImageUrl() {
		return get("imageUrl");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
