package com.future.link.convenience.model;

import com.future.link.convenience.model.base.BasePublish;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Publish extends BasePublish<Publish> {
	public static final Publish dao = new Publish();
	
	/**
	 * 把imageUrl转化成绝对地址
	 */
	private String showUrl;
	
	public String getShowUrl() {
		return showUrl;
	}

	public void setShowUrl(String showUrl) {
		this.put("showUrl", showUrl);
		this.showUrl = showUrl;
	}
}
