package com.future.link.system.model;

import com.future.link.system.model.base.BaseAdvertising;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Advertising extends BaseAdvertising<Advertising> {
	public static final Advertising dao = new Advertising();
	
	/**
	 * 把imageUrl转化成绝对地址
	 */
	private String showUrl;
	
	public String getShowUrl() {
		return showUrl;
	}

	public void setShowUrl(String showUrl) {
		this.put("showUrl", showUrl);
		this.showUrl = showUrl;
	}
}
