package com.future.link.carousel.model;

import com.future.link.carousel.model.base.BaseAdvertising;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Advertising extends BaseAdvertising<Advertising> {
	public static final Advertising dao = new Advertising();
}
